syntax = "proto3";

package ethereum.engine.v1;

import "proto/engine/v1/execution_engine.proto";
import "proto/engine/v1/electra.proto";
import "proto/eth/ext/options.proto";

option go_package = "github.com/OffchainLabs/prysm/v6/proto/engine/v1;enginev1";

message ExecutionPayloadEnvelope {
  ExecutionPayloadDeneb payload = 1;
  ExecutionRequests execution_requests = 2;
  uint64 builder_index = 3 [ (ethereum.eth.ext.cast_type) =
  "github.com/OffchainLabs/prysm/v6/"
      "consensus-types/primitives.ValidatorIndex" ];
  bytes beacon_block_root = 4 [ (ethereum.eth.ext.ssz_size) = "32" ];
  uint64 slot = 5 [
    (ethereum.eth.ext.cast_type) =
        "github.com/OffchainLabs/prysm/v6/consensus-types/primitives.Slot"
  ];
  repeated bytes blob_kzg_commitments = 6 [
    (ethereum.eth.ext.ssz_size) = "?,48",
    (ethereum.eth.ext.ssz_max) = "max_blob_commitments.size"
  ];
  bytes state_root = 7 [ (ethereum.eth.ext.ssz_size) = "32" ];
}

message SignedExecutionPayloadEnvelope {
  ExecutionPayloadEnvelope message = 1;
  bytes signature = 2 [ (ethereum.eth.ext.ssz_size) = "96" ];
}
